# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd1c08c71ecfec6cb99d7d2de9105b8f6a0ad771c0416546b700e2fc3e63a27f83fb2b0d885c00734814815c19842f65cbdda19ddc422e58084451227ab4e6b

test:
  secret_key_base: 25dd396a234c0504b0b80aa8eb1b106212e32d2dfdbb5d0f3387f57b96c7fe94c562d07d4b5fc08a54de5e9db027595594b9d57e319e838fa753534791a90bff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
